### ISSUE TITLE
From where is this repository checked?

### ISSUE THREAD

**Issue by jameswhite** [github/pong#1]
We've got a key:
![screen shot 2015-05-18 at 1 51 57 pm](https://cloud.githubusercontent.com/assets/20034/7690690/75ce5e62-fd7b-11e4-8b14-6742370bf47e.png)
that seems to be being used to check this repository [regularly](https://chat.githubapp.com/messages/1478025463/context)

https://github.campfirenow.com/room/538883/uploads/6640627/Screen+Shot+2015-05-18+at+2.43.27+PM.png

I'm just trying to determine where the client-side (and thus the ssh private key) exist for this check so I can roll it.

**Comment by jnewland** [comment]
`/gitmon top cpu -r github/pong` has some IPs.

**Comment by jameswhite** [comment]
right on, thanks @jnewland

**Comment by jameswhite** [comment]
looks like nugget and octostatus nodes
